version: "3.8"

services:
  faiss:
    build:
      context: ./faiss
    ports:
      - "8080:8000"
    container_name: faiss-service
    runtime: nvidia  # Only Faiss service requires GPU access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Expose all GPUs to Faiss

  fasttrack-api:
    build:
      context: ./fasttrack-api
    ports:
      - "6060:5000"
    container_name: fasttrack-api
    depends_on:
      - faiss
    # No GPU access needed for the API service