version: "3.8"

services:
  faiss:
    build:
      context: ./faiss
    ports:
      - "8080:8000"
    container_name: faiss-service

  fasttrack-api:
    build:
      context: ./fasttrack-api
    ports:
      - "6060:5000"
    container_name: fasttrack-api
    depends_on:
      - faiss

